### PR TITLE
Add all touched to rasterize

### PR DESCRIPTION
**Pull request by LiamRMoore**
Simple addition of all_touched kwarg for geocube.rasterize.rasterize_image which propagates immediately to rasterio.

 - [X] Tests added
 - [X] Fully documented, including `docs/history.rst` for all changes and `docs/geocube.rst` for new API

### CODE REVIEW

**Comment by snowman2** [comment]
This looks great, thanks :+1:

Would you mind compressing the file in the tests?
```python
comp = dict(zlib=True, complevel=5)
encoding = {var: comp for var in xds.data_vars}
xds.to_netcdf(netcdf_path, encoding=encoding)
```

**Comment by snowman2** [comment]
Also, would you like to squash your commits? Or would you mind if I squash on merge?

**Comment by LiamRMoore** [comment]
No worries! Thank you for this nice library. Have compressed and squashed, just let me know if there's anything else.

**Comment by snowman2** [comment]
The changes look good :+1:, waiting on one more set of eyes on it and I think we should be good to merge it in.

**Review by justingruca — APPROVED** [review]

**Comment by snowman2** [comment]
Thanks again @LiamRMoore :+1:

**Pull request merged**
